version: '3.8'

services:
  db:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: blogapp
      POSTGRES_USER: blogapp
      POSTGRES_PASSWORD: blogapp

    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    command: postgres

  app:
    container_name: app-container
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      DEBUG_MODE: "True"
      DATABASE_HOST: db

    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./app
        target: /app
    restart: unless-stopped
    depends_on:
      - db

volumes:
  pgdata:
