version: '3.8'

services:
  db:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_DB: django_blog
      POSTGRES_USER: blogger
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    command: postgres

  app:
    container_name: app-container
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file: app/.env
    environment:
      - DJANGO_SETTINGS_MODULE=blog.settings.development
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./app
        target: /app
    depends_on:
      - db

volumes:
  pgdata:
